# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43a8a280a25b13fa2abd81e75f41e8ea8e3a362f37ff09e295c68946105251f137330fd34889d047179b3aa5c093acc8abc057495c21695edc19d5ff9904fe64

test:
  secret_key_base: a8716c7fbf39a8d3bf5cf09e2254e4789fdbd90dcefd253b0853fdb8c017cb903d75efa32d22315ab39026ff75ba70ab8db0b41a01cb0ca6a7d333436ca2fa43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
